### ISSUE TITLE
Test on our own videos?

### ISSUE THREAD

**Issue by noobtoob4lyfe** [visinf/fldr-vfi#1]
Thanks for sharing this great work!
Is there a script that allows us to test our own footage using the pretrained model?

**Comment by altair199797** [comment]
Thank you!
Unfortunately Not. But you could write a dataset class and add it to the Testsets. Just Like X_Test or Inter4K_Test.
The Feature you request will however be added soon.

**Comment by altair199797** [comment]
Feature is added.
