### ISSUE TITLE
run_on_your_images.py  example?

### ISSUE THREAD

**Issue by noobtoob4lyfe** [visinf/fldr-vfi#2]
Thanks for adding the run_on_your_images.py script!

Can you give an example command with arguments for a typical use of this script?  I'm having trouble figuring out where to put my images and how to use a pretrained model.  Thanks!

**Comment by altair199797** [comment]
Sure.
The Main() function of run_on_your_images.py already is example Code. It evaluates on X-Test and uses the function "run_on_images()" to execute the model.
The prepare_model() function must be called beforehand to get the model and the needed args. Then you can run "run_on_images()". The Parameters of this function are already explained in the code.
